package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserInfo record);

    //校验用户名是否存在
    int checkUsername(String username);
    //根据用户名和密码查询
    UserInfo selectByUsernameAndPassword(@Param("username") String username,
                                         @Param("password") String password);

    //校验邮箱是否存在
    int checkEmail(String email);

    /**
     * 根据username查询密保问题
     */
    String selectQuestionByUsername(String username);

    /**
     * 校验答案
     */

    int checkAnswerByUsernameAndQuestion(@Param("username") String username,
                                         @Param("question") String question,
                                         @Param("answer") String answer);

    /**
     * 根据用户名更新密码
     */
    int updatePasswordByUsername(@Param("username") String username,
                                 @Param("password") String passwordNew);
}